### ISSUE TITLE
PAGE 2 "HOME" -> INDEX: Card rendering issue

### ISSUE THREAD

**Issue by elsie-d** [elsie-d/savory-secrets#67]
Expected Behavior: When user clicks "home" from Page 2, Index page should load with recipe cards.
Actual Behavior: When "home" is clicked from Page 2, recipe cards do not render on Index.

**Comment by BennyBlanco88** [comment]
fixed, the navbar home href was capitalized as Index.html when it needed to be lowercase index.html
